### ISSUE TITLE
Update AWS extension

### ISSUE THREAD

**Issue by stackus** [projectjellyfish/api#1060]
The AWS extension needs to be updated to provision and deprovision three types of products.

- [x] EC2 (Compute)
  - [x] provision
  - [x] deprovision
  * Inputs
    - Input AMI image id/name
    - Input instance size
    - Input VPC
    - Input Security Group
  * Outputs
    - Output authentication info (as possible keypair, login info, other)
    - Output public IP address
- [x] S3 (Storage)
  - [x] provision
  - [x] deprovision
  * Inputs
    - Input public/private
  * Outputs
    - Output bucket name
- [x] RDS (Database)
  - [x] provision
  - [x] deprovision
  * Inputs
    - Input db flavor
    - Input login info (username?, password?)
    - Input schema file?
  * Outputs
    - Output connection info (ip address?, port?)

The inputs and outputs are not concrete, these are the most likely basic needs that I can think of. I also have not broken the inputs into product and order questions. Difficult, or admin-y inputs should be product questions. The less technicals the end user needs to enter the better.

**Comment by mafernando** [comment]
Added first pass at implementation of EC2 (Compute) with provision and deprovision [here](https://github.com/projectjellyfish/jellyfish-aws/tree/feature/update-products).

Working on S3 and RDS currently.

**Comment by mafernando** [comment]
Just pushed up the S3 bucket product and service changes to the update branch.
 
S3 buckets are created as private by default. To make them public would require the involvement of ACL policies. 

Tagging the public/private input requirement as something to be handled as separate task. Will also need to add access controls for S3 bucket CRUD.

**Comment by mafernando** [comment]
Per feedback from @chrishample and @stackus, went ahead an created two resources to bring in EC2 to Jellyfish:

1) A [`develop`](https://github.com/projectjellyfish/jellyfish-aws/tree/develop) branch in `jellyfish-aws` which adds basic implementation of EC2 product type and service onto the existing `master` branch with provision and deprovision (both wired through delayed jobs). RDS and S3 code exists, but are commented out for now. 

2) PR https://github.com/projectjellyfish/api/pull/1085 in JF api which replaces the `jellyfish-aws` reference from RubyGems with one pointing to the `develop` branch under the `jellyfish-aws` repo on our GitHub.

**Comment by mafernando** [comment]
Just pushed up an implementation of the RDS product type and service with provision and deprovision to the [jellyfish-aws/feature/update-products](https://github.com/projectjellyfish/jellyfish-aws/tree/feature/update-products) branch.

RDS is a bit tricker to implement because its provisioning takes longer than a  barebones EC2 or S3 instance. As such, connection information doesn't become available until after 15-20 minutes have passed. 

This implementation makes the call to provision a new RDS and then marks the service as running in JF when in AWS the service is still being provisioned. We will probably need to add a polling job to run in the background and retrieve connection information when the service is finished being created in AWS.

**Comment by mafernando** [comment]
@stackus, made the following changes to the [jellyfish-aws/feature/update-products](https://github.com/projectjellyfish/jellyfish-aws/tree/feature/update-products) branch:
- moved admin user and password questions from product to order on RDS. 
- made AWS clients public in provider to reference from services instead of duplicating code in each product. 
- copied over generic template for service to AWS services so that buttons and outputs are consistent between the extension and core.
