### ISSUE TITLE
Change contents of Order Items grid > 'Service' column on the '/order/:oid' page

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#426]
<a href="https://github.com/sonejah21"><img src="https://avatars.githubusercontent.com/u/5269893?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sonejah21](https://github.com/sonejah21)**
_Friday Mar 13, 2015 at 17:19 GMT_
_Originally opened as https://github.com/projectjellyfish/ux/issues/287_

----

Currently the 'Service' column has 'Service' Services in it. The issue speaks for itself. 
I need to figure out which options are supposed to be in this column. It could be 'Type of Service' as a header, with the categories of service listed below (infrastructure, platforms, databases, etc.). It could also be removed if we do not feel it serves much of a purpose.

![uploads/ed1729e4-bb20-4b89-977d-ef20564f0771/Screen Shot 2015-03-13 at 1.09.47 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fed1729e4-bb20-4b89-977d-ef20564f0771%2FScreen+Shot+2015-03-13+at+1.09.47+PM.png)

**Comment by chriskacerguis** [comment]
<a href="https://github.com/tangerine007"><img src="https://avatars.githubusercontent.com/u/4211939?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tangerine007](https://github.com/tangerine007)**
_Thursday Mar 26, 2015 at 20:30 GMT_

----

Should also make this a clickable link if it is kept as it is linking to the Order Item Details/Service page. See Issue #298 as I think the Order Item ID should link to the Order Item Details page, especially if you remove this column.

**Comment by sonejah21** [comment]
Current page (orders/:id):
![uploads/23c6b05a-5ad8-4e0a-b01e-6ddd1dfda650/Screen Shot 2015-04-28 at 10.29.00 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F23c6b05a-5ad8-4e0a-b01e-6ddd1dfda650%2FScreen+Shot+2015-04-28+at+10.29.00+PM.png)

The Order Item ID & the corresponding Product both currently link to the Product page which I think is accurate, since there isn't a separate page for the Order Item ID.
