### ISSUE TITLE
Project start date before end date validation

### ISSUE THREAD

**Issue by tangerine007** [projectjellyfish/api#504]
Project creation allows end date to be before start date.
![image](https://cloud.githubusercontent.com/assets/4211939/7096682/9ca23e24-df9d-11e4-9ae7-de04ddfa60e0.png)

**Comment by sonejah21** [comment]
What I changed: 
- The start_date is set to the current day or a day in the future
- The end_date is set to a date after the start_date
- I removed the ability to view the weeks that were situated at left since they did not come in with italics, and therefore looked awkward in normal typeface.

In the future, we'll have to add the styling to the disabled dates so they're visually different than the enabled dates. (I'm thinking a light gray background?)
