### ISSUE TITLE
Text location issue

### ISSUE THREAD

**Issue by EvanBerner** [projectjellyfish/api#514]
Text does not align properly with the side bar.
![text issue](https://cloud.githubusercontent.com/assets/11509735/7122605/a01f402a-e1ea-11e4-8b93-7f46d58e9811.png)

**Comment by sonejah21** [comment]
Fixed in branch bug.ux-514-content-margins-issue by adding equivalent margin to dl element inside of this page only. 

![uploads/60653999-9a85-403b-aa8a-a6efe01c9de0/Screen Shot 2015-04-30 at 11.52.34 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F60653999-9a85-403b-aa8a-a6efe01c9de0%2FScreen+Shot+2015-04-30+at+11.52.34+AM.png)
