### ISSUE TITLE
Add seed data for project approval

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#519]
We need to add seed data (and possibly update the schema) for "approval", "status" and "archived".  Looks like we are returning null on some of those

**Comment by mafernando** [comment]
Sure, will look at [`sample:demo`](https://github.com/projectjellyfish/api/blob/master/lib/tasks/sample.rake#L69-L77) specifically for the following attributes on projects:
- [status](https://github.com/projectjellyfish/api/blob/master/db/schema.rb#L297)
- [approval](https://github.com/projectjellyfish/api/blob/master/db/schema.rb#L298)
- [archived](https://github.com/projectjellyfish/api/blob/master/db/schema.rb#L299)

**Comment by mafernando** [comment]
@chriskacerguis - looks like `status` and `approval` are being set in `sample:demo`. The only attribute not present is archived. Where are you seeing the aforementioned nulls?

Am reaching out to @OBCENEIKON to figure out how the `archived` attribute is intended to be [used](https://github.com/projectjellyfish/api/commit/87d6dc97f678b89bfadd0cb721bcb7be85a63d82).

**Comment by chriskacerguis** [comment]
@jklarfeld does this make sense, or do you have any other questions on this?

**Comment by jklarfeld** [comment]
Well, ideally, I'd need a list of possible values for these fields.  

Archived, I would assume, is a boolean field.  A project can either be Archived, or not Archived, there is no third state.  So returning nil for the field is an invalid boolean. So that would mean either Ruby can't do booleans correctly, or it's not a boolean field, hence the need for the list of possible values.

Finally, I see no way in the web interface of archiving a project, would it be possible for one or two of the seed objects to be inserted as archived so I can test this functionality?

**Comment by mafernando** [comment]
@jklarfeld - `archived` is a [timestamp](https://github.com/projectjellyfish/api/blob/master/db/schema.rb#L299), not a boolean.
