### ISSUE TITLE
Product Type dropdown is missing styles

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#539]
On /admin/products/create the Product Type dropdown is missing styles

![screen shot 2015-04-16 at 7 52 26 am](https://cloud.githubusercontent.com/assets/2414647/7181129/a604c576-e40d-11e4-8ec9-9fb19205cc12.png)

**Comment by sonejah21** [comment]
Added the correct class to this dropdown so that it is formatted like the other inputs/textareas in the form. Also added in the help div to keep spacing between fields in form. If we really want to get picky about the carets at the right side of the dropdown matching, I'll have to spend more time on this, as the icon dropdown receives its styling of the caret from the ui-select. 

![uploads/7b751632-0f3d-41fd-9e04-66802dcb23fe/Screen Shot 2015-04-22 at 12.44.33 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7b751632-0f3d-41fd-9e04-66802dcb23fe%2FScreen+Shot+2015-04-22+at+12.44.33+PM.png)

**Comment by sonejah21** [comment]
Unrelated tests won't pass, so I reopened this as a Working file again until it's actually able to pass and be merged in. The branch is: bug/ux-539-create-product-styling-V2
