### ISSUE TITLE
In /projects number fields are not consistent

### ISSUE THREAD

**Issue by jklarfeld** [projectjellyfish/api#551]
In the returned JSON for /projects, `budget`, `spent`, `monthly_spend` are returned as numbers when they are integers, and strings when they are floating point numbers.

Ideally, they'd all be numbers, as floating point numbers are perfectly acceptable in the JSON standard based on the FSM at [json.org](json.org)

![fem](http://json.org/number.gif)

**Comment by mafernando** [comment]
I noticed that `budget` is defined as a float in the DB and was returning a JSON number regardless if the underlying value was zero or nonzero. 

Based on that observation, I got project `spent` to return as a JSON number by changing the project spent from a decimal to a float in the DB. 

Since `monthly_spent` comes from a method defined on the project model, I modified that method to cast the result as float which resulted in the response returning as JSON numbers for all cases.

The implementation of this can be found on [this](https://github.com/projectjellyfish/api/pull/558) branch.

**Comment by mafernando** [comment]
@jklarfeld - this should be merged into master now.

**Comment by jklarfeld** [comment]
Thanks! Let me know when it's redeployed and I'll give it a test.

**Comment by mafernando** [comment]
@jklarfeld - just redeployed to jellyfish dev on heroku.
