### ISSUE TITLE
/Services has no documentation and returns inconsistently.

### ISSUE THREAD

**Issue by jklarfeld** [projectjellyfish/api#562]
The `/Services` endpoint currently had no documentation whatsoever.

Additionally, and perhaps more worryingly, a service object as returned by a `GET` to `/Services` looks like this:
```
{
    "product_id" : 18,
    "provision_status" : null,
    "project_description" : "Project description",
    "id" : 20,
    "latest_alert_id" : null,
    "service_description" : "Ruby on Rails Stack",
    "service_name" : "Rails Stack",
    "project_id" : 3,
    "project_name" : "Blog"
  }
```

But a service object returned when bundled with a `GET` to `/Projects` like the 16 parameter leviathan found in the web interface (`/Projects?includes[]=services` for example) looks like this:

```
{
		"id": 17,
		"order_id": 5,
		"cloud_id": 1,
		"product_id": 5,
		"service_id": null,
		"provision_status": null,
		"created_at": "2015-04-23T19:59:40.456Z",
		"updated_at": "2015-04-23T19:59:40.456Z",
		"deleted_at": null,
		"project_id": 2,
		"miq_id": null,
		"uuid": "4b0185f0-c309-4a1a-b3be-c9c0438b945d",
		"setup_price": 1.99,
		"hourly_price": 0.004,
		"monthly_price": 0.1,
		"payload_request": null,
		"payload_acknowledgement": null,
		"payload_response": null,
		"latest_alert_id": null,
		"status_msg": null
	}
```

**Comment by mafernando** [comment]
@jklarfeld - this is a work in progress. Services are a proxy for OrderItems. Rather than add unnecessary paths and logic to the OrderItemsController, @AllenBW and I created the ServicesController to return custom JSON data that he could then feed into D3 and other ux functionality. No documentation yet b/c we are still adding/refactoring this controller.
