### ISSUE TITLE
Where's "Organization Name"?

### ISSUE THREAD

**Issue by jklarfeld** [projectjellyfish/api#572]
In the main 'Dashboard' of the App (iOS), the title of the menubar shows an "Organization Name", and perhaps I missed it, but I don't see this coming back anywhere.  One would think it would be in the login `POST` response, but it isn't there, nor is it in a call the `/staff/:staff_id/settings`.  I would suggest it be returned in the `/staff/sign_in` `POST` because it would be a shame to endure the latency of another web request for a single string.

**Comment by calebthompson** [comment]
Surprisingly, I've never seen the organization model. It turns out that it's completely isolated in this repo, unrelated to any other models, so I don't have a way I can include an org with a staff since they aren't related models.

Is it being used in the iOS side? Does it need to be? We might be able to just remove the model and api completely...

@chriskacerguis thoughts?

Looks like @stackus and @cparratto build out the feature so far - am I missing something here?

FWIW, there's an organizations endpoint where you could pull them all down but I'm not sure how you'd decide which one to use if there's multiple. The dev server doesn't actually have any.

**Comment by jklarfeld** [comment]
If it helps, it's just a single label on the main Dashboard of the app (iOS).
![img_0198](https://cloud.githubusercontent.com/assets/1403387/7378887/b9312850-edbe-11e4-9d56-25de13b3db9e.PNG)

**Comment by calebthompson** [comment]
Unless somebody chimes in, I might suggest just hard-coding that to say "Jellyfish" and call it a day. The organizations feature doesn't seem well enough constructed to give you the answer you want, and I doubt we'll end up with org switching any time soon so there won't be a lot of meaning to the organization name anyhow.

**Comment by mafernando** [comment]
i agree with @calebthompson :+1:

**Comment by jklarfeld** [comment]
So long as we get @chriskacerguis approval I'm completely fine with that.

**Comment by chriskacerguis** [comment]
Let's hard code for the time being.
