### ISSUE TITLE
Adding a user properly?

### ISSUE THREAD

**Issue by jklarfeld** [projectjellyfish/api#576]
When adding a user to a project, do I send a `POST` to `/projects/:id/staff/:id` or a `PUT` to `/staff/:id/projects/:id`? What about removing them? There is currently no documentation for either endpoint, so it is unclear what the `POST`/`PUT` bodies should contain, with regards to the newly added user's authorization level ('Administrator', 'Editor', 'Collaborator').

**Comment by calebthompson** [comment]
If possible, hold off on assigning staff to projects. We have an ongoing change that will remove the current implementation and replace it with groups, which you can sneak a peek at here: https://github.com/projectjellyfish/api/compare/groups#diff-e13da661e24d850049dbbcfb12f01addR33

**Comment by jklarfeld** [comment]
That's closer, but it doesn't really explain how to control Alerts, I mean, I can't send a `POST` with a JSON body that looks like:
```
{ 
     "alerts" : "Hey send less alerts and stuff please"
}
```

The same goes for getting the settings.  I have to assume there are some default alert settings, otherwise you'd never get alerts.

**Comment by calebthompson** [comment]
@jklarfeld we've merged the Roles changes. Users are now organized into groups which give them access to projects. The [Groups api](http://jellyfish-core-dev.herokuapp.com/documentation/1.0/groups.html) will allow you to create groups and to add users to groups (by updating the staff_ids field - make sure to pass back the whole array).

Groups can be added to projects to provide access. The [Memberships api](http://jellyfish-core-dev.herokuapp.com/documentation/1.0/memberships.html) handles this. It also allows you to set a Role, which defines the abilities group members have on projects their group has access to.

The [Roles API](http://jellyfish-core-dev.herokuapp.com/documentation/1.0/roles.html) allows specifying and updating these Roles.

Except for Memberships, all of these APIs are admin-only. Memberships (adding groups to projects) is controlled by a Role, and is always allowed for an admin.

Let me know if you have any questions on this.

**Comment by calebthompson** [comment]
Update: instead of messing with the staff_ids field, which can be cumbersome, you can now use the [associations api](http://jellyfish-core-dev.herokuapp.com/documentation/1.0/associations.html) to add and remove staff from groups without messing with the whole array.

**Comment by jklarfeld** [comment]
I have lots of questions!

1. Is there any documentation for these new endpoints? All the links on the documentation pages are blank.

2. Is there any test data for these new features? Currently the test endpoint contains no groups.

3. What if a project has no groups? 

4. Why are Roles an entire endpoint? It seems like this is an enum value, making another request seems unnecessary.  Wouldn't it be much easier to include at least the read-only version of the available roles with the project information? 

5. Is there any way of getting staff information in bulk?  Take for example a screen where you show who is currently on a project (again, I can't see any documentation, so bear with me here), I would first have to gather all the group IDs for the project (which can be bundled with /projects), and then for each group I have to do **another** request for every single staffID I find to get their information to even display their name.  So say a small project has two groups, and 10 users total.  That's at best 11 API calls to show who is on the project. 1 call gets the project info and the group IDs, and then a call for every single person I need to show. This is a poor approach regardless of perspective.

6. From what I can tell, adding a user to the project (worst case) involves a call to get the available users, then another call to create a group, then another call to add them to the group, then another call to update their roll. 

7. It would seem that projects do not contain groups as standard, this seems like an oversight.

**Comment by calebthompson** [comment]
> Is there any documentation for these new endpoints? All the links on the documentation pages are blank.

I think there's been a miscommunication about docs. Those pages document the parameters we expect and allow when you make a request to the API. In that sense, the pages aren't "blank". However, they don't document what the server returns. There's no good way on our end to do this, but as usual you can make an educated guess about what a GET request would return based on the parameters to a POST or PUT request. cc @chriskacerguis 

> Is there any test data for these new features? Currently the test endpoint contains no groups.

There is not. We have somebody working on this for you so hopefully that'll change soon. cc @OBCENEIKON 

> What if a project has no groups?

Admins can always access projects. Standard users can't see or change a project that they don't have access to through a group.

> Why are Roles an entire endpoint? It seems like this is an enum value, making another request seems unnecessary. Wouldn't it be much easier to include at least the read-only version of the available roles with the project information?

Roles are something that admins can change, so they're different for each installation. There's no default roles in the system. Each role's abilities are also modifiable, of course.

> Is there any way of getting staff information in bulk? Take for example a screen where you show who is currently on a project (again, I can't see any documentation, so bear with me here), I would first have to gather all the group IDs for the project (which can be bundled with /projects), and then for each group I have to do another request for every single staffID I find to get their information to even display their name. So say a small project has two groups, and 10 users total. That's at best 11 API calls to show who is on the project. 1 call gets the project info and the group IDs, and then a call for every single person I need to show. This is a poor approach regardless of perspective.

Good point. I'm not sure we need to list out the staff for projects, but it's reasonable to include in the available `includes` for projects (which would inline the resources instead of sending ids). This is already available for groups. https://github.com/projectjellyfish/api/issues/669

> From what I can tell, adding a user to the project (worst case) involves a call to get the available users, then another call to create a group, then another call to add them to the group, then another call to update their roll.

Yeah since we manage staff in groups instead of onto projects, it probably makes sense for the app to allow admins to put users into groups, then only deal with groups at the project level instead of trying to add them to projects directly.

> It would seem that projects do not contain groups as standard, this seems like an oversight.

Not sure I understand, but possibly you're referring to not including the project's groups in the /projects/:id response, in which case you can specify them in the `includes` array to have them included.

**Comment by chriskacerguis** [comment]
No further responses.  Closing.
