### ISSUE TITLE
Token auth returns incorrect status code

### ISSUE THREAD

**Issue by jklarfeld** [projectjellyfish/api#596]
This was a pretty hard one to find, but once we started testing on multiple iPhones it occurred:

If you log in from one iPhone from a given account, you're given a token to use with requests.

If you log in from another iPhone (or any other service that uses token auth instead of cookies) to the same account, you get a new token and the old one is invalidated.

However, once the token is invalidated, use of the original token doesn't result in a `401 Unauthorized` coming back, but instead a `500` is returned.  Since `500` is generic, I have no idea when there is actually an issue with the service, or if the user needs to re-auth.

Suggest a change to 401 when the token being used is invalid.

**Comment by chriskacerguis** [comment]
Spoke to @masonforest and @calebthompson looks like we need to have a "tokens" table, b/c there could be multiple clients and this would be easier.  Sending this to @masonforest

**Comment by masonforest** [comment]
Seem like there are 2 issues here:

1. The api is returning 500 instead of 401 when a request is unauthorized. This should be fixed in this PR: https://github.com/projectjellyfish/api/pull/612

2. We would like to be able to connect to Jellyfish from multiple devices at the same time without invalidating the other clients' tokens. I made a card for that here: https://github.com/projectjellyfish/api/issues/613

**Comment by mafernando** [comment]
Verified API is returning 401 for unauthorized requests and that multiple tokens can be requested from API to authenticate without invalidating existing sessions. Closing ticket.
