### ISSUE TITLE
When provisioning payload_request in the order_items table is not getting populated

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#621]
When provisioning payload_request in the order_items table is not getting populated.  It should be getting what we are sending as part of the provisioning request.

**Comment by OBCENEIKON** [comment]
The changes I am working on now will fix this.

**Comment by OBCENEIKON** [comment]
It looks like the response from ManageIQ has been immediate, so the response has been being stored in payload_response instead of payload_acknowledgement. Testing with MIQ, I haven't even seen any callback being made from ManageIQ.
I'm assuming with Fog, thats the same thing going on. There aren't any callbacks being made to the endpoint, so the response is being stored in payload_response instead of payload_acknowldegement.

**Comment by OBCENEIKON** [comment]
Closing, this is not an issue.
