### ISSUE TITLE
/order/:id/service/:id not showing server info or provisioning status

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#631]
/order/:id/service/:id not showing server info or provisioning status

**Comment by AllenBW** [comment]
awwwwww no pretty screenshot? FINE. will get to this soon.

**Comment by AllenBW** [comment]
Right on, progress update, ends up the state to the service instance view from order history was incorrect, so that's resolved

The second and primary issue, of ip and host name not showing up are directly related to the absence of the api/server endpoint  (*server*, instead of *service*).  

server.rb (app\modules\manage_iq_client) lives, but in it's present form does not appear to tie to any a specific order number service number.  possibly derivable from a server name and id (if the id matches its service number)

**Comment by AllenBW** [comment]
necessary ux changes added, requires seed update for changes to be realized
