### ISSUE TITLE
Jellyfish Cart Rejigger

### ISSUE THREAD

**Issue by AllenBW** [projectjellyfish/api#635]
Present State: generic message is thrown when any amount of cart items for a single project exceed that projects budget, but we don't have the particulars of which project or what the value it exceeds the budget by

- [ ] Improve grouping in cart by project, relating cart contents cost of each project to project budget and overall cart cost

- [ ] build configurable alert scenarios for cart overflow behavior, two use cases: 
 1. refuse of items to the cart for a project when the cart contents (with addition) would exceed budget, throw a lovely descriptive message about the encountered behavior and suggest alternative COAs's
 2. allow cart additions to exceed budget but display the offending resources from each project on checkout (refuse checkout)

other suggestions welcome.

**Comment by chriskacerguis** [comment]
I'm thinking that it should be a setting.  If ALLOW_OVER_BUDGET_CHECKOUT (or whatever we call it) is true, then the user will be presented with a warning that says basically "your cart exceeds your total budget by $0.00".  If  ALLOW_OVER_BUDGET_CHECKOUT they should get an error saying that they cannot checkout because the amount is greater than the budget.

**Comment by gnklausner** [comment]
I'm slightly concerned about the code that was merged, as it I'm fairly certain it will throw the "exceeded budget" error if you disconnect your WiFi. In line with what @chriskacerguis mentioned, there will probably need to be some sort of logic beyond what currently exists.

**Comment by mafernando** [comment]
closing this per @AllenBW.
