### ISSUE TITLE
Add hostname/ip to the api/services

### ISSUE THREAD

**Issue by AllenBW** [projectjellyfish/api#649]
related to  /order/:id/service/:id not showing server info or provisioning status #631 

presence of hostname and ip address of a service is necessary on the /services api endpoint

**Comment by mafernando** [comment]
Issues:
- server payload response is dynamic and varies with the cloud service provider and product type. since these payloads are inconsistent, it is difficult to depend on any one attribute existing. 
- server payload response for VMWare is too complex to store as a JSON blob

**Comment by chriskacerguis** [comment]
proposal: create a subhash that contains a predefined set of attributes which are stubbed by default and populated from payload response if they are contained therein

Proposal Accepted!

proposal: don't save the entire response, just the relevant bits pertaining to looking up the instance

What should we save?  I would rather save everything, that way we don't need to come back add "add" more stuff.

**Comment by mafernando** [comment]
See [here](https://github.com/projectjellyfish/jellyfish-fog/issues/12#issuecomment-104392794) for context. 

I added `binding.pry` in my code after the server returns the payload response.

 ```
[3] pry(#<Jellyfish::Fog::VMWare::Infrastructure>)> server.to_json.length
SystemStackError: stack level too deep
  ```

At least for our vSphere instance, converting the server response to JSON causes a SytemStackError as above. Trying to figure out if this is due to an [infinite loop](http://stackoverflow.com/questions/7569759/paperclip-and-json-stack-level-too-deep) issue.

**Comment by mafernando** [comment]
Implmented via PR https://github.com/projectjellyfish/api/pull/664

**Comment by AllenBW** [comment]
:+1: DO IT! looks good.
