### ISSUE TITLE
Tried to order AWS Small, "Order Could Not Be Placed At This Time"

### ISSUE THREAD

**Issue by jnegrelli** [projectjellyfish/api#812]
Created a new project & approved it.
Added AWS Small to shopping cart
Could not complete checkout, red error box appeared

**Comment by stackus** [comment]
@jnegrelli Was this done on a new local install or on a preexisting host?

**Comment by jnegrelli** [comment]
I created a new project & then couldn't check out w/ new services

**Comment by mafernando** [comment]
Hi Jerry, 

I believe the issue was with the demo DB. I checked the logs and the component responsible for provisioning seemed to be stuck in a spin lock. It seems to be working now. 

I created an approved Test Project:
![image](https://cloud.githubusercontent.com/assets/9356425/8621165/b198d160-26e9-11e5-89a0-b75f410d815a.png)

Added AWS Small to my cart:
![image](https://cloud.githubusercontent.com/assets/9356425/8621186/dd9b4f9a-26e9-11e5-86ba-8e787c9b8a7a.png)

Hit Checkout:
![image](https://cloud.githubusercontent.com/assets/9356425/8621213/ffe6f46e-26e9-11e5-958e-12939800135b.png)

And got the order to pass through:
![image](https://cloud.githubusercontent.com/assets/9356425/8621220/08cd04ba-26ea-11e5-8f17-bd6309365c52.png)

So it appears as a service in the Project:
![image](https://cloud.githubusercontent.com/assets/9356425/8621227/113ae798-26ea-11e5-94e9-1cbb0af05652.png)

If you want, I can go through and flush the DB so you can start from a clean slate.

**Comment by mafernando** [comment]
closing this for now since its demo configuration and not code issue.

@jnegrelli - reach out to me on Slack if you need to reset the DB.
