### ISSUE TITLE
Compare modal is missing some parts

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#965]
Modal is missing the following parts:

* Extra properties for each product being compared
* Restore order button

**Comment by AllenBW** [comment]
@chriskacerguis what additional properties are desired?

**Comment by stackus** [comment]
Products have additional properties, the metadata information like Disk Size, ... These should be listed and compared. If two products do share a property it is compared on the same row. If a product shares no properties with another product then nothing is compared by being displayed on the same row but all properties are still listed.

- Product A has properties 1, 2, 3
- Product B has properties 1, 3, 4
- Product C has properties 5, 6

Rows for 1, 2, 3, 4, 5, 6 are all displayed but some are empty because the property does not exist for the product.

**Comment by AllenBW** [comment]
right on!  totally digging this. une question pour favor, presently comparison happens between selected items as they appear in `http://localhost:3000/api/v1/products`. We cherry pick each field to be compared presently, wondering if additional properties should be expected on `/v1/products`. If so, will they be in collected inside of some pretty object that can be combed through or more pickin' is necessary (if more picking what fields).

**Comment by stackus** [comment]
No, `order_questions` are not values to compare, they're questions for the ordering process. You'll want the answers given during the product creation process. These are saved as `answers` on each `Product`.

**Comment by AllenBW** [comment]
`provisioning_answers`?

**Comment by stackus** [comment]
No, `answers`.

- `Product` model : https://github.com/projectjellyfish/api/blob/master/app/models/product.rb
- `Answer` model : https://github.com/projectjellyfish/api/blob/master/app/models/answer.rb
- `Product.answers` relationship : https://github.com/projectjellyfish/api/blob/master/app/models/concerns/answers.rb

**Comment by AllenBW** [comment]
:+1: Roger that. On it.

**Comment by AllenBW** [comment]
breaking out order buttons at the bottom of each products column cuz its special, #1002
